version: '3'
services:
  certs:
    build: .
    env_file:
      - .env
    volumes:
      - ./domains.txt:/tmp/domains.txt:ro
      - ./certs/:/persistent/certs
      - persistent:/persistent
    tmpfs:
      - /tmp
    read_only: true

volumes:
  persistent: